Disaster Simulator
==================
:toc:
:toc-placement: preamble
:ages: AGES

This is the source code of the Disaster Simulator for Multi-Agent Sysmte, currently supporting flooding environments. This simulator is inspired by the https://multiagentcontest.org/2018/[Multi-Agent Programming Contest (MAPC)] and was initially developed by a team of students of http://www.ages.pucrs.br/[AGES] at PUCRS.
In this repository, you will find all the information required to run the simulator. 

// Need some preamble to get TOC:
{empty}

== Prepare the Environment
In order to execute our simulator you need to have Python 3.6 installed on your machine and a configuration file like the one on the files folder (one can use that for tests).


== Run the Disaster Simulator
After having the environment configured, you can run the simulation in a terminal at the root of this project directory, just type the following command in the terminal:

`python3 start_system.py <configuration-file>.json`

> Note: Do not use the "<" or ">", it was just to highlight that it is the desired configuration file. Also, the path to the configuration file is considered to be from the root of the project, so if one wants to use the configuration file inside the files folder, one should pass to the simulation "files/config.json".


== Contributing to this Project

João Vitor Bernardi Severo


